src/Entity/Order.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\OrderRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
#[ORM\HasLifecycleCallbacks]
class Order
{
    public const STATUS_CART = 'cart';

    public const STATUS_NEW = 'new';

    public const STATUS_PAID = 'paid';

    public const STATUS_CANCELED = 'canceled';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private DateTimeImmutable $createdAt;

    #[ORM\Column]
    private DateTimeImmutable $updatedAt;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank]
    private ?string $lastname = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank]
    #[Assert\Regex('/^\+?\d/', message: 'Nieprawidłowy format numeru telefonu')]
    private ?string $phone = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank]
    #[Assert\Email(message: 'Adres {{ value }} nie jest prawidłowym adresem e-mail.')]
    private ?string $email = null;

    #[ORM\Column]
    private bool $invoice = false;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(groups: ['invoice'])]
    private ?string $company = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(groups: ['invoice'])]
    private ?string $taxId = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(groups: ['invoice'])]
    private ?string $country = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(groups: ['invoice'])]
    private ?string $city = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(groups: ['invoice'])]
    private ?string $zipCode = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(groups: ['invoice'])]
    private ?string $street = null;

    #[ORM\Column(length: 255)]
    private string $status = self::STATUS_CART;

    #[ORM\Column]
    private ?int $value = 0;

    #[ORM\Column]
    private bool $deleted = false;

    /**
     * @var Collection<int, OrderItem>
     */
    #[ORM\OneToMany(mappedBy: 'orderRef', targetEntity: OrderItem::class, cascade:['persist', 'remove'], orphanRemoval: true)]
    private Collection $items;

    #[ORM\Column(type: 'string', nullable: true)]
    private ?string $uuid = null;

    public function __construct()
    {
        $this->createdAt = new DateTimeImmutable();
        $this->updatedAt = new DateTimeImmutable();
        $this->items = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->name && $this->lastname ? $this->name . ' ' . $this->lastname : (string) $this->id;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function isInvoice(): ?bool
    {
        return $this->invoice;
    }

    public function setInvoice(bool $invoice): self
    {
        $this->invoice = $invoice;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(?string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getTaxId(): ?string
    {
        return $this->taxId;
    }

    public function setTaxId(?string $taxId): self
    {
        $this->taxId = $taxId;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zipCode;
    }

    public function setZipCode(?string $zipCode): self
    {
        $this->zipCode = $zipCode;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getValue(): ?int
    {
        return $this->value;
    }

    public function setValue(int $value): self
    {
        $this->value = $value;

        return $this;
    }

    #[ORM\PreUpdate]
    public function preUpdate(): void
    {
        $this->updatedAt = new DateTimeImmutable();
    }

    public function addItem(OrderItem $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items->add($item);
            $item->setOrderRef($this);
        }

        return $this;
    }

    public function removeItems(): self
    {
        foreach ($this->getItems() as $item) {
            $this->removeItem($item);
        }

        return $this;
    }

    /**
     * @return Collection<int, OrderItem>
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function removeItem(OrderItem $item): self
    {
        if ($this->items->removeElement($item) && $item->getOrderRef() === $this) {
            $item->setOrderRef(null);
        }

        return $this;
    }

    public function getTotalItems(): int
    {
        return $this->items->count();
    }

    public function getTotalPrice(): float
    {
        $price = 0;

        foreach ($this->items as $item) {
            $price += $item->getProduct()?->getPrice();
        }

        return round($price / 100, 2);
    }

    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function setUuid(string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    public function markAsPaid(): void
    {
        $this->status = self::STATUS_PAID;
    }

    public function cancel(): void
    {
        $this->status = self::STATUS_CANCELED;
    }

    public function isDeleted(): ?bool
    {
        return $this->deleted;
    }

    public function setDeleted(bool $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }
}

src/Entity/Product.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\ProductRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Vich\UploaderBundle\Mapping\Annotation\UploadableField;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[Vich\Uploadable]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private string $name = '';

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    /**
     * @var Collection<int, Category>
     */
    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'products')]
    private Collection $category;

    #[ORM\Column]
    private DateTimeImmutable $createdAt;

    #[ORM\Column]
    private DateTimeImmutable $updatedAt;

    #[ORM\Column]
    private int $price = 0;

    /**
     * @var Collection<int, ProductImage>
     */
    #[ORM\OneToMany(mappedBy: 'product', targetEntity: ProductImage::class, cascade: ['persist'], orphanRemoval: true)]
    private Collection $images;

    #[UploadableField(mapping: 'product', fileNameProperty: 'fileName', size: 'fileSize')]
    private ?File $file = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $fileName = '';

    #[ORM\Column(type: 'integer', nullable: true)]
    private ?int $fileSize = 0;

    #[ORM\Column(type: 'integer')]
    private int $validity = 0;

    #[ORM\ManyToOne]
    private ?Template $template;

    #[ORM\Column]
    private bool $availableAsGift = false;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $shortDescription = null;

    /**
     * @var Collection<int, OrderItem>
     */
    #[ORM\OneToMany(mappedBy: 'product', targetEntity: OrderItem::class)]
    private Collection $orderItems;

    #[ORM\Column]
    private bool $active = false;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $place = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $time = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $peoples = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $duration = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $weight = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $helpText = null;

    public function __construct()
    {
        $this->category = new ArrayCollection();
        $this->createdAt = new DateTimeImmutable();
        $this->updatedAt = new DateTimeImmutable();
        $this->images = new ArrayCollection();
        $this->orderItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->category->contains($category)) {
            $this->category->add($category);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->category->removeElement($category);

        return $this;
    }

    public function getCreatedAt(): ?DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDisplayPrice(): ?float
    {
        return round($this->price / 100, 2);
    }

    #[ORM\PreUpdate]
    public function preUpdate(): void
    {
        $this->updatedAt = new DateTimeImmutable();
    }

    /**
     * @return Collection<int, ProductImage>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(ProductImage $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setProduct($this);
        }

        return $this;
    }

    public function removeImage(ProductImage $image): self
    {
        if ($this->images->removeElement($image) && $image->getProduct() === $this) {
            $image->setProduct(null);
        }

        return $this;
    }

    public function getFile(): ?File
    {
        return $this->file;
    }

    public function setFile(File $file): void
    {
        $this->file = $file;
    }

    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    public function setFileName(?string $fileName): self
    {
        $this->fileName = $fileName;

        return $this;
    }

    public function getFileSize(): ?int
    {
        return $this->fileSize;
    }

    public function setFileSize(?int $fileSize): self
    {
        $this->fileSize = $fileSize;

        return $this;
    }

    public function getValidity(): int
    {
        return $this->validity;
    }

    public function setValidity(int $validity): self
    {
        $this->validity = $validity;

        return $this;
    }

    public function getTemplate(): ?Template
    {
        return $this->template;
    }

    public function setTemplate(?Template $template): self
    {
        $this->template = $template;

        return $this;
    }

    public function isAvailableAsGift(): ?bool
    {
        return $this->availableAsGift;
    }

    public function setAvailableAsGift(bool $availableAsGift): self
    {
        $this->availableAsGift = $availableAsGift;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->shortDescription;
    }

    public function setShortDescription(?string $shortDescription): self
    {
        $this->shortDescription = $shortDescription;

        return $this;
    }

    /**
     * @return Collection<int, OrderItem>
     */
    public function getOrderItems(): Collection
    {
        return $this->orderItems;
    }

    public function addOrderItem(OrderItem $orderItem): self
    {
        if (!$this->orderItems->contains($orderItem)) {
            $this->orderItems->add($orderItem);
            $orderItem->setProduct($this);
        }

        return $this;
    }

    public function removeOrderItem(OrderItem $orderItem): self
    {
        if ($this->orderItems->removeElement($orderItem) && $orderItem->getProduct() === $this) {
            $orderItem->setProduct(null);
        }

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function validThru(): DateTimeImmutable|null
    {
        $now = new DateTimeImmutable();

        if ($this->validity === 0) {
            return null;
        }

        return $now->modify('+ ' . $this->validity . ' days');
    }

    public function getPlace(): ?string
    {
        return $this->place;
    }

    public function setPlace(?string $place): self
    {
        $this->place = $place;

        return $this;
    }

    public function getTime(): ?string
    {
        return $this->time;
    }

    public function setTime(?string $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getPeoples(): ?string
    {
        return $this->peoples;
    }

    public function setPeoples(?string $peoples): self
    {
        $this->peoples = $peoples;

        return $this;
    }

    public function getDuration(): ?string
    {
        return $this->duration;
    }

    public function setDuration(?string $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getWeight(): ?string
    {
        return $this->weight;
    }

    public function setWeight(?string $weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    public function getHelpText(): ?string
    {
        return $this->helpText;
    }

    public function setHelpText(?string $helpText): self
    {
        $this->helpText = $helpText;

        return $this;
    }
}

src/Controller/Front/CategoryController.php
<?php

declare(strict_types=1);

namespace App\Controller\Front;

use App\Entity\Category;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CategoryController extends AbstractController
{
    #[Route(path: '/category/{id}', name: 'category')]
    public function category(Category $category): Response
    {
        return $this->render('front/category.html.twig', [
            'category' => $category,
        ]);
    }
}

templates/front/cart.html.twig
{% extends 'base.html.twig' %}

{% block title %}Twój koszyk | {{ menu.settings.name }}{% endblock %}

{% block body %}
    {% include 'front/top-menu.html.twig' %}
    <div class="container mx-auto">
        {% for message in app.flashes('danger') %}
            <div class="bg-app-red text-white font-medium mb-4 py-2 px-8 mt-4">
                {{ message }}
            </div>
        {% endfor %}

        {% set formErrors = form.vars.errors.form.getErrors(true) %}

        {% if formErrors|length %}
            <div class="bg-app-red text-white font-medium mb-4 py-2 px-8 mt-4">
                <ul>
                    {% for error in formErrors %}
                        <li>{{ error.message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        <h2 class="text-center font-semibold text-2xl mb-12 uppercase mt-20">Koszyk</h2>
        <div class="grid lg:grid-cols-3 gap-4 mt-12 items-start">
            <div class="lg:col-span-2 px-4 order-2 lg:order-1">
                <p class="font-bold text-2xl mb-4 text-app-gold">Twoje produkty</p>
                {% for item in cart.items %}
                    <div class="bg-app-gray-100 p-8 mb-5 text-app-blue-300">
                        <div class="grid lg:grid-cols-4 gap-12 relative">
                            <a href="{{ path('removeItem', {id: item.id}) }}" class="text-app-gray-200 font-bold absolute -top-2 right-0">X</a>
                            <img src="{{ asset('images/products/' ~ item.product.fileName) }}" alt="{{ item.product.name }}" class="w-full h-40 object-cover">
                            <div class="col-span-3">
                                <p class="font-bold text-lg mb-3">
                                    <a href="{{ path('product', {id: item.product.id}) }}">
                                        {{ item.product.name }}
                                    </a>
                                </p>
                                <p class="text-xl font-bold text-app-gold mb-8">
                                    {{ item.product.displayPrice|format_currency('PLN', locale='pl') }}
                                </p>
                                {% if item.product.availableAsGift %}
                                    <p class="text-sm font-medium mb-2">Voucher do wykorzystania do dnia: {{ item.product.validThru?item.product.validThru|date('Y-m-d'):'Bezterminowo' }}</p>
                                    {% if item.gift %}
                                        <div class="uppercase text-sm font-medium flex items-center">
                                            <span class="fill-app-blue-300 transition-all mr-3">{% include('icons/gift.html.twig') %}</span>
                                            <span>Voucher na prezent</span>
                                        </div>
                                    {% else %}
                                        <div class="uppercase text-sm font-medium flex items-center">
                                            <span class="fill-app-blue-300 transition-all mr-3">{% include('icons/voucher.html.twig') %}</span>
                                            <span>Voucher dla Ciebie</span>
                                        </div>
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}

                <p class="font-bold text-2xl mb-4 text-app-gold mt-10">Dane osobowe</p>
                {{ form_start(form, {'attr': {'class': 'mt-4 p-4 bg-light'}}) }}
                {{ form_row(form._token) }}
                    <div class="mt-8">
                        <div class="grid gap-5 grid-cols-2">
                            <div>
                                {{ form_label(form.name, null, {'label_attr': {'class': 'font-semibold'}}) }}<span class="text-app-red ml-1">*</span>
                                {{ form_widget(form.name, {'attr': {'class': 'w-full rounded-md border border-app-gray-200 px-5 py-3 mt-1'}}) }}
                            </div>
                            <div>
                                {{ form_label(form.lastname, null, {'label_attr': {'class': 'font-semibold'}}) }}<span class="text-app-red ml-1">*</span>
                                {{ form_widget(form.lastname, {'attr': {'class': 'w-full rounded-md border border-app-gray-200 px-5 py-3 mt-1'}}) }}
                            </div>
                            <div class="col-span-2">
                                {{ form_label(form.phone, null, {'label_attr': {'class': 'font-semibold'}}) }}<span class="text-app-red ml-1">*</span>
                                {{ form_widget(form.phone, {'attr': {'class': 'w-full rounded-md border border-app-gray-200 px-5 py-3 mt-1'}}) }}
                            </div>
                            <div class="col-span-2">
                                {{ form_label(form.email, null, {'label_attr': {'class': 'font-semibold'}}) }}<span class="text-app-red ml-1">*</span>
                                {{ form_widget(form.email, {'attr': {'class': 'w-full rounded-md border border-app-gray-200 px-5 py-3 mt-1'}}) }}
                            </div>
                            <div class="col-span-2 p-8 bg-app-gray-100">
                                {{ form_widget(form.invoice) }}
                                {{ form_label(form.invoice, null, {'label_attr': {'class': 'font-semibold ml-1'}}) }}
                            </div>
                            <div id="invoiceFields" class="grid gap-5 grid-cols-2 col-span-2 max-h-0 opacity-0 -z-10 transition-all relative">
                                <div class="col-span-2">
                                    {{ form_label(form.company, null, {'label_attr': {'class': 'font-semibold'}}) }}<span class="text-app-red ml-1">*</span>
                                    {{ form_widget(form.company, {'attr': {'class': 'w-full rounded-md border border-app-gray-200 px-5 py-3 mt-1'}}) }}
                                </div>
                                <div class="col-span-2">
                                    {{ form_label(form.taxId, null, {'label_attr': {'class': 'font-semibold'}}) }}<span class="text-app-red ml-1">*</span>
                                    {{ form_widget(form.taxId, {'attr': {'class': 'w-full rounded-md border border-app-gray-200 px-5 py-3 mt-1'}}) }}
                                </div>
                                <div class="col-span-2">
                                    {{ form_label(form.country, null, {'label_attr': {'class': 'font-semibold'}}) }}<span class="text-app-red ml-1">*</span>
                                    {{ form_widget(form.country, {'attr': {'class': 'w-full rounded-md border border-app-gray-200 px-5 py-3 mt-1'}}) }}
                                </div>
                                <div class="col-span-2">
                                    {{ form_label(form.street, null, {'label_attr': {'class': 'font-semibold'}}) }}<span class="text-app-red ml-1">*</span>
                                    {{ form_widget(form.street, {'attr': {'class': 'w-full rounded-md border border-app-gray-200 px-5 py-3 mt-1'}}) }}
                                </div>
                                <div>
                                    {{ form_label(form.zipCode, null, {'label_attr': {'class': 'font-semibold'}}) }}<span class="text-app-red ml-1">*</span>
                                    {{ form_widget(form.zipCode, {'attr': {'class': 'w-full rounded-md border border-app-gray-200 px-5 py-3 mt-1'}}) }}
                                </div>
                                <div>
                                    {{ form_label(form.city, null, {'label_attr': {'class': 'font-semibold'}}) }}<span class="text-app-red ml-1">*</span>
                                    {{ form_widget(form.city, {'attr': {'class': 'w-full rounded-md border border-app-gray-200 px-5 py-3 mt-1'}}) }}
                                </div>
                            </div>
                        </div>
                        <div class="w-full bg-app-gray-200 h-px my-8"></div>
                        <div>
                            {{ form_widget(form.terms) }}
                            {{ form_label(form.terms, null, {'label_attr': {'class': 'font-semibold ml-1 text-app-gray-200 text-sm'}}) }}
                        </div>
                        <div class="flex justify-end w-full">
                            <button class="group flex items-center justify-center bg-app-blue-300 hover:bg-app-gold p-4 px-12 transition-all mt-4">
                                <span class="text-sm text-app-gold uppercase font-bold tracking-wider group-hover:text-app-blue-300 transition-all">Kupuję i płacę</span>
                                <span class="ml-2 stroke-app-gold group-hover:stroke-app-blue-300 transition-all">{% include('icons/arrows-right.html.twig') %}</span>
                            </button>
                        </div>
                    </div>
                {{ form_end(form, {'render_rest': false}) }}
            </div>
            <div class="lg:col-span-1 lg:sticky lg:top-4 px-4 order-1 lg:order-2">
                <p class="font-bold text-2xl mb-4 text-app-gold">Twoje zamówienie</p>
                <div class="bg-app-gray-100 p-8">
                    <p class="font-bold text-lg">Forma dostawy:</p>
                    <p class="text-lg mb-3">E-voucher PDF</p>
                    <p class="font-bold text-lg">Forma płatności:</p>
                    <p class="text-lg mb-3">iMoje (płatności online)</p>
                    <img src="{{ asset('images/misc/imoje-dark.png') }}" alt="i-moje">
                    <div class="w-full bg-app-gray-200 h-px my-8"></div>
                    <div class="flex items-start justify-between flex-wrap">
                        <p class="font-bold text-2xl uppercase">Do zapłaty: </p>
                        <p class="font-bold text-2xl">{{ cart.totalPrice|format_currency('PLN', locale='pl') }}</p>
                    </div>

                </div>
            </div>
        </div>
    </div>
    {% include 'front/footer.html.twig' %}
{% endblock %}

{% block scripts %}
    <script>
        let invoiceFields = document.getElementById('invoiceFields');
        let invoiceCheckbox = document.getElementById('{{ form.invoice.vars.id }}');

        invoiceCheckbox.addEventListener("change", function() {
            if (this.checked) {
                showField(invoiceFields);
            } else {
                hideField(invoiceFields);
            }
        });

        function showField(field) {
            field.classList.remove('max-h-0', 'opacity-0', '-z-10');
            field.classList.add('opacity-100');
            let fields = field.getElementsByTagName('input');
            for (const element of fields) {
                setRequired(element);
            }

        }

        function hideField(field) {
            field.classList.add('max-h-0', 'opacity-0', '-z-10');
            field.classList.remove('opacity-100');
            let fields = field.getElementsByTagName('input');
            for (const element of fields) {
                unsetRequired(element);
            }
        }

        function setRequired(field) {
            field.setAttribute('required', '');
        }

        function unsetRequired(field) {
            field.removeAttribute('required');
        }
    </script>
{% endblock %}

templates/front/category.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ category.name }} | {{ menu.settings.name }}{% endblock %}

{% block body %}
    {% include 'front/top-menu.html.twig' %}
    <div class="container mx-auto mt-20">
        <div class="grid lg:grid-cols-3 gap-8 mb-20 place-content-center px-4">
            {% for product in category.activeProducts %}
                <div class="bg-app-gray-300">
                    <a href="{{ path('product', {id: product.id}) }}">
                        <img src="{{ asset('images/products/' ~ product.fileName) }}" alt="{{ product.name }}" class="w-full h-64 object-cover">
                    </a>
                    <div class="flex items-center justify-center">
                        <p class="bg-app-gold text-white font-bold px-4 py-2 -mt-10">{{ product.displayPrice|format_currency('PLN', locale='pl') }}</p>
                    </div>
                    <div class="p-8">
                        <h2 class="text-base font-bold border-b border-app-gold pb-4">{{ product.name }}</h2>
                        <div class="my-4 text-sm leading-8 font-medium">{{ product.shortDescription|striptags|u.truncate(200, '...', false)|raw }}</div>

                        <a href="{{ path('product', {id: product.id}) }}" class="group flex items-center justify-center w-full bg-app-blue-300 hover:bg-app-gold p-4 transition-all">
                            <span class="text-sm text-app-gold uppercase font-bold tracking-wider group-hover:text-app-blue-300 transition-all">Zobacz szczegóły</span>
                            <span class="ml-2 stroke-app-gold group-hover:stroke-app-blue-300 transition-all">{% include('icons/arrows-right.html.twig') %}</span>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="my-2 description text-center px-4">
            {{ category.description|raw }}
        </div>
    </div>
    {% include 'front/footer.html.twig' %}
{% endblock %}

templates/front/page.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ page.title }} | {{ menu.settings.name }}{% endblock %}

{% block body %}
    {% include 'front/top-menu.html.twig' %}
    <div class="container mx-auto mt-20">
        <h2 class="text-center font-semibold text-2xl mb-12">{{ page.title }}</h2>
        <div class="description px-4">
            {{ page.content|raw }}
        </div>
    </div>
    {% include 'front/footer.html.twig' %}
{% endblock %}